import { useCallback, useEffect, useState } from "react";
import { Amplify } from "aws-amplify";
import { Authenticator } from "@aws-amplify/ui-react";
import { getCurrentUser, signOut as amplifySignOut } from "aws-amplify/auth";
import App from "./App";

function SignedIn({ user, onAuthenticated }) {
  // Pass the authenticated user back to the app and close the sign-in dialog.
  useEffect(() => {
    onAuthenticated(user);
  }, [onAuthenticated, user]);

  return <p role="status">Signing you in...</p>;
}

function AppBootstrap() {
  const [backendState, setBackendState] = useState("loading");
  const [errorMessage, setErrorMessage] = useState("");
  const [user, setUser] = useState(null);
  const [authOpen, setAuthOpen] = useState(false);
  const handleAuthenticated = useCallback((signedInUser) => {
    setUser(signedInUser);
    setAuthOpen(false);
  }, []);

  useEffect(() => {
    let active = true;

    // Load the outputs generated by Amplify; without them, run the local preview.
    async function configureBackend() {
      try {
        const response = await fetch("/amplify_outputs.json");
        if (response.status === 404) {
          if (active) {
            setBackendState("local");
          }
          return;
        }
        if (!response.ok) {
          throw new Error(`Backend configuration request failed (${response.status}).`);
        }

        if (!response.headers.get("content-type")?.includes("application/json")) {
          if (active) {
            setBackendState("local");
          }
          return;
        }

        const outputs = await response.json();
        if (Object.keys(outputs).length === 0) {
          if (active) {
            setBackendState("local");
          }
          return;
        }
        if (
          !outputs.auth?.user_pool_id ||
          !outputs.auth?.user_pool_client_id ||
          !outputs.data?.url
        ) {
          throw new Error("The Amplify backend configuration is incomplete.");
        }

        Amplify.configure(outputs);
        try {
          const currentUser = await getCurrentUser();
          if (active) {
            setUser(currentUser);
          }
        } catch (error) {
          // An unauthenticated visitor is expected; other auth errors should be shown.
          if (error?.name !== "UserUnAuthenticatedException") {
            throw error;
          }
        }

        if (active) {
          setBackendState("cloud");
        }
      } catch (error) {
        if (active) {
          setErrorMessage(error.message);
          setBackendState("error");
        }
      }
    }

    configureBackend();
    return () => {
      active = false;
    };
  }, []);

  if (backendState === "loading") {
    return <p role="status">Loading Civics Flashcards...</p>;
  }
  if (backendState === "error") {
    return (
      <p role="alert">
        Could not initialize cloud sign-in: {errorMessage}
      </p>
    );
  }
  if (backendState === "local") {
    return <App />;
  }

  return (
    <>
      <App
        cloudEnabled
        user={user}
        signIn={() => setAuthOpen(true)}
        signOut={async () => {
          await amplifySignOut();
          setUser(null);
        }}
      />
      {authOpen && !user && (
        <div
          className="auth-modal"
          role="presentation"
          onMouseDown={(event) => {
            if (event.target === event.currentTarget) {
              setAuthOpen(false);
            }
          }}
        >
          <section
            className="auth-modal__content"
            role="dialog"
            aria-modal="true"
            aria-label="Sign in or create an account"
          >
            <button
              className="auth-modal__close"
              aria-label="Close sign-in dialog"
              onClick={() => setAuthOpen(false)}
            >
              ×
            </button>
            <Authenticator>
              {({ user: authenticatedUser }) => (
                <SignedIn
                  user={authenticatedUser}
                  onAuthenticated={handleAuthenticated}
                />
              )}
            </Authenticator>
          </section>
        </div>
      )}
    </>
  );
}

export default AppBootstrap;
